name: Change Progress Label on Issues - Done

on:
  issues:
    types: [closed]

jobs:
  change-label:
    permissions:
      contents: read
      issues: write
    runs-on: ubuntu-latest
    steps:
    - name: Remove progress label on Issue
      uses: actions-cool/issues-helper@v3
      with:
        actions: 'remove-labels'
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.issue.number }}
        labels: 'To Do,In Progress,In Review'
        
    - name: Add progress label on Issue
      uses: actions-cool/issues-helper@v3
      with:
        actions: 'add-labels'
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.issue.number }}
        labels: 'Done'
